FROM ubuntu:22.04

ARG COMPILER=gcc
ARG NANO_SANITIZER
ARG NANO_COVERAGE

# Install build dependencies
COPY ./ci/prepare/linux /tmp/prepare
RUN /tmp/prepare/prepare.sh

COPY ./ /root/src
WORKDIR /root/src

# Build tests
RUN --mount=type=cache,target=/root/src/build \
    ci/build-tests.sh

RUN --mount=type=cache,target=/root/src/build \
    cp -r /root/src /root/out

RUN ldconfig

WORKDIR /root/out
USER root

ENV PATH="${PATH}:/usr/bin"
ENV PATH="${PATH}:/root/out/build"
CMD ["core_test"]