ARG ENV_REPOSITORY=nanocurrency/nano-env
FROM ${ENV_REPOSITORY}:base

# TEMP WORKAROUND: Compatibility with clang backtrace fix
RUN backtrace_file=$(find /usr/lib/gcc/ -name 'backtrace.h' | head -n 1) && test -f $backtrace_file && ln -s $backtrace_file /tmp/backtrace.h

ARG REPOSITORY=nanocurrency/nano-node
LABEL org.opencontainers.image.source https://github.com/$REPOSITORY
